version: "3"

services:
  app:
    build:
      args:
        user: puspa
      context: ./volumes/php
      dockerfile: Dockerfile
    image: puspa
    container_name: puspa-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ${APP_SRC}:/var/www
    networks:
      - puspa
    depends_on:
      - db
      - nginx
      # - cache
      # - mail