version: "3"

services:
  db:
    image: mysql:8
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./volumes/mysql:/docker-entrypoint-initdb.d
    networks:
      - creaper

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_SRC}:/var/www
      - ./volumes/nginx:/etc/nginx/conf.d
    networks:
      - creaper

  # mail:
  #   image: 'mailhog/mailhog:latest'
  #   ports:
  #     - 1025:1025
  #     - 8025:8025

  # cache:
  #   image: redis:alpine
  #   volumes:
  #     - ./volumes/cache:/data
  #   ports:
  #     - 63792:6379

networks:
  creaper:
    driver: bridge