version: "3"

services:
  app:
    build:
      args:
        user: ${APP_NAME}
      context: ./volumes/php
      dockerfile: Dockerfile
    image: ${APP_NAME}
    container_name: ${APP_NAME}-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ${APP_SRC}:/var/www
    networks:
      - creaper
    depends_on:
      - db
      - nginx
      # - cache
      # - mail